//! Report generator (SUM-37).
//!
//! Renders collected time series and gate results into a self-contained Markdown report with
//! tables and inline Unicode sparklines — no plotting dependencies, so a report can be produced
//! anywhere the harness runs and committed as text.

use crate::gates::{GateResult, GateStatus};
use crate::sampler::TimeSeries;
use serde::{Deserialize, Serialize};
use std::fmt::Write as _;

const MIB: f64 = 1024.0 * 1024.0;

/// Per-run summary distilled from one launcher × scenario time series.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct RunSummary {
    /// Launcher name.
    pub launcher: String,
    /// Scenario slug.
    pub scenario: String,
    /// Peak tracked-subtree footprint, mebibytes.
    pub peak_root_mib: f64,
    /// First→last growth of the tracked subtree, mebibytes.
    pub growth_mib: f64,
    /// Worst-case attributed fraction.
    pub min_attributed_fraction: f64,
    /// Mean per-sample cost, microseconds.
    pub mean_sample_us: f64,
    /// Sampling overhead percent at the run's interval.
    pub overhead_pct: f64,
    /// Number of samples.
    pub samples: usize,
    /// Peak number of processes in the launched tree.
    pub peak_procs: usize,
    /// Sparkline of the tracked subtree footprint over time.
    pub footprint_spark: String,
}

impl RunSummary {
    /// Distill a time series into a summary at the given sampling interval.
    pub fn from_series(launcher: &str, scenario: &str, ts: &TimeSeries, interval_ms: u64) -> Self {
        let footprint: Vec<f64> = ts
            .records
            .iter()
            .map(|r| r.root_subtree_bytes as f64 / MIB)
            .collect();
        Self {
            launcher: launcher.to_string(),
            scenario: scenario.to_string(),
            peak_root_mib: ts.peak_root_subtree_bytes() as f64 / MIB,
            growth_mib: ts.root_subtree_growth_bytes() as f64 / MIB,
            // The launched-tree attribution is the meaningful metric (see sampler docs).
            min_attributed_fraction: if ts.is_empty() {
                1.0
            } else {
                ts.min_tree_attributed_fraction()
            },
            mean_sample_us: ts.mean_sample_duration_us(),
            overhead_pct: ts.overhead_fraction(interval_ms) * 100.0,
            samples: ts.records.len(),
            peak_procs: ts.peak_root_process_count(),
            footprint_spark: sparkline(&footprint),
        }
    }
}

/// Render a run of the benchmark as a Markdown document.
pub fn render_markdown(title: &str, summaries: &[RunSummary], gates: &[GateResult]) -> String {
    let mut out = String::new();
    let _ = writeln!(out, "# {title}\n");
    let _ = writeln!(
        out,
        "_Generated by `memmux-bench`. Competitor launchers appear only when their binary was \
present on `PATH`; absent tools are omitted rather than estimated (§19.5)._\n"
    );

    // Per-run table.
    let _ = writeln!(out, "## Runs\n");
    let _ = writeln!(
        out,
        "_\"Tree attributed\" is the fraction of the launched process tree \
mapped back to the owning task — the Phase-0 attribution metric._\n"
    );
    let _ = writeln!(
        out,
        "| Launcher | Scenario | Procs | Peak MiB | Growth MiB | Tree attributed | Mean sample (µs) | Overhead % | Samples | Footprint |"
    );
    let _ = writeln!(
        out,
        "| --- | --- | ---: | ---: | ---: | ---: | ---: | ---: | ---: | --- |"
    );
    for s in summaries {
        let _ = writeln!(
            out,
            "| {} | {} | {} | {:.1} | {:+.1} | {:.1}% | {:.0} | {:.3} | {} | `{}` |",
            s.launcher,
            s.scenario,
            s.peak_procs,
            s.peak_root_mib,
            s.growth_mib,
            s.min_attributed_fraction * 100.0,
            s.mean_sample_us,
            s.overhead_pct,
            s.samples,
            s.footprint_spark,
        );
    }

    // Gates table.
    let _ = writeln!(out, "\n## Launch gates (§18.5)\n");
    let _ = writeln!(out, "| Gate | Status | Detail |");
    let _ = writeln!(out, "| --- | --- | --- |");
    for g in gates {
        let _ = writeln!(
            out,
            "| {} | {} | {} |",
            g.name,
            status_badge(g.status),
            g.detail
        );
    }

    out
}

fn status_badge(status: GateStatus) -> &'static str {
    match status {
        GateStatus::Pass => "✅ pass",
        GateStatus::Fail => "❌ fail",
        GateStatus::Skipped => "⚪ skipped",
    }
}

/// Render a slice of values as a Unicode block sparkline.
///
/// An empty slice yields an empty string; a flat slice yields the lowest block.
pub fn sparkline(values: &[f64]) -> String {
    const BLOCKS: [char; 8] = ['▁', '▂', '▃', '▄', '▅', '▆', '▇', '█'];
    if values.is_empty() {
        return String::new();
    }
    let min = values.iter().cloned().fold(f64::INFINITY, f64::min);
    let max = values.iter().cloned().fold(f64::NEG_INFINITY, f64::max);
    let range = max - min;
    values
        .iter()
        .map(|&v| {
            if range <= f64::EPSILON {
                BLOCKS[0]
            } else {
                let idx = ((v - min) / range * (BLOCKS.len() as f64 - 1.0)).round() as usize;
                BLOCKS[idx.min(BLOCKS.len() - 1)]
            }
        })
        .collect()
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::sampler::TimeSeriesRecord;

    fn rec(elapsed: u64, subtree: u64) -> TimeSeriesRecord {
        TimeSeriesRecord {
            t_unix_ms: 0,
            elapsed_ms: elapsed,
            launcher: "memmux".into(),
            scenario: "leak".into(),
            sample_duration_us: 300,
            process_count: 1,
            total_bytes: subtree,
            owned_bytes: subtree,
            shared_bytes: 0,
            escaped_bytes: 0,
            unknown_bytes: 0,
            attributed_fraction: 1.0,
            root_subtree_bytes: subtree,
            root_process_count: 2,
            tree_attributed_fraction: 1.0,
        }
    }

    #[test]
    fn sparkline_shapes() {
        assert_eq!(sparkline(&[]), "");
        assert_eq!(sparkline(&[5.0, 5.0, 5.0]), "▁▁▁");
        let s = sparkline(&[0.0, 1.0, 2.0, 3.0]);
        assert_eq!(s.chars().count(), 4);
        assert_eq!(s.chars().next().unwrap(), '▁');
        assert_eq!(s.chars().last().unwrap(), '█');
    }

    #[test]
    fn summary_from_series_captures_growth() {
        let ts = TimeSeries::new(vec![
            rec(0, (100.0 * MIB) as u64),
            rec(100, (180.0 * MIB) as u64),
        ]);
        let s = RunSummary::from_series("memmux", "leak", &ts, 1000);
        assert!((s.peak_root_mib - 180.0).abs() < 0.5);
        assert!((s.growth_mib - 80.0).abs() < 0.5);
        assert_eq!(s.samples, 2);
        assert_eq!(s.footprint_spark.chars().count(), 2);
    }

    #[test]
    fn markdown_contains_tables_and_badges() {
        let ts = TimeSeries::new(vec![rec(0, (50.0 * MIB) as u64)]);
        let summaries = vec![RunSummary::from_series("raw-baseline", "burst", &ts, 1000)];
        let gates = vec![
            GateResult {
                name: "Attribution".into(),
                status: GateStatus::Pass,
                detail: "min 99%".into(),
            },
            GateResult {
                name: "Resume".into(),
                status: GateStatus::Skipped,
                detail: "Phase 2".into(),
            },
        ];
        let md = render_markdown("MemMux Phase 0 benchmark", &summaries, &gates);
        assert!(md.contains("## Runs"));
        assert!(md.contains("## Launch gates"));
        assert!(md.contains("raw-baseline"));
        assert!(md.contains("✅ pass"));
        assert!(md.contains("⚪ skipped"));
    }
}
